run:
  concurrency: 4
  timeout: 15m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - goimports
    - revive

linters-settings:
  revive:
    rules:
      - name: dot-imports
        disabled: true
