services:
  go-rest-chi:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_ADDRESS=:8081
      - ALLOWED_ORIGINS=*,http://localhost:3000
      - JWT_SECRET_KEY=hoge
      - PIYO_GRAPHQL_ENDPOINT=http://host.docker.internal:8082/query
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_DOGSTATSD_PORT=8125
    volumes:
      - go-modules:/go/pkg/mod
    depends_on:
      - datadog-agent

  datadog-agent:
    image: datadog/agent:latest
    ports:
      - "8126:8126"
      - "8125:8125/udp"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=ap1.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      # メトリクス関連の設定を追加
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true  # 他のコンテナからのメトリクス受信を許可
      - DD_DOGSTATSD_ORIGIN_DETECTION=true   # コンテナタグの自動検出
      - DD_DOGSTATSD_TAG_CARDINALITY=high    # タグの詳細度設定
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /tmp/datadog-agent-run:/opt/datadog-agent/run:rw

volumes:
  go-modules:
